name: Deploy to Railway

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy Backend to Railway
        uses: OtnielDev/railway-action@main
        with:
          railway_token: ${{ secrets.RAILWAY_TOKEN }}
          environment: production
          serviceName: erp-backend
